import type { SkillGroup } from "./types";

/** 5 groups = the 5 particle clusters in the About latent-space scene. */
export const skillGroups: SkillGroup[] = [
  {
    id: "frontend",
    label: "Frontend",
    philosophy: "pixels are the last mile of the pipeline",
    skills: [
      "Next.js",
      "React",
      "Redux Toolkit",
      "TanStack Query",
      "Tailwind CSS",
      "Material-UI",
      "shadcn/ui",
    ],
  },
  {
    id: "backend",
    label: "Backend",
    philosophy: "the API contract is the architecture",
    skills: [
      "Node.js",
      "NestJS",
      "Express.js",
      "FastAPI",
      "RESTful APIs",
      "JWT Auth",
      "OAuth 2.0",
      "Stripe Connect",
      "Google Calendar API",
      "Google Meet API",
    ],
  },
  {
    id: "cloud",
    label: "Cloud & DevOps",
    philosophy: "cattle not pets, always one push away",
    skills: [
      "AWS (S3 · EC2 · Lambda · ELB · API GW · VPC)",
      "GCP",
      "Docker",
      "Kubernetes",
      "Helm",
      "Rancher",
      "GitHub Actions",
      "NGINX",
      "Linux",
    ],
  },
  {
    id: "ai-data",
    label: "AI & Databases",
    philosophy: "search is reasoning over structure",
    skills: [
      "RAG",
      "Multi-modal AI Systems",
      "Gemini API",
      "Pinecone",
      "PostgreSQL",
      "DynamoDB",
      "MongoDB",
      "Prisma ORM",
      "Firebase",
    ],
  },
  {
    id: "architecture",
    label: "Architecture & Design",
    philosophy: "build for the swap, measure the seams",
    skills: [
      "Microservices Architecture",
      "Clean Architecture",
      "Event-Driven Design",
      "TypeScript",
      "JavaScript (ES6+)",
      "Python",
      "C++",
      "SQL",
    ],
  },
];
